name = "Xuefeng_Yomi_Modpack"
author = "AzureCrab"
version = "beta-0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "189c573565ef5489d7f1085e82e36485989e9a00eba047ef14a0544d91b35edb"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
