name = "Dreamscape_Odyssey"
author = "AzureCrab"
version = "beta-0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "95125c5ac2eae6cf6d46c7d830c0de31d1a4bbcc2092e06ae25a7073ae94db75"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
